<template>
  <div class="p-4">
    <form
      class="rounded shadow-lg mx-5 bg-blue-200 grid grid-rows gap-4 px-4 py-3"
      @submit.prevent="handleSubmit"
    >
      <div class="font-bold">FHE August 12, 2024</div>
      <div class="grid grid-rows gap-4">
        <div class="" style="width: 200px">
          <label for="column">Column:</label>
          <input
            id="column"
            v-model="column"
            type="text"
            maxlength="1"
            required
            class="border-gray-200 border-2 rounded"
            style="max-width: 50px"
          />
        </div>
        <div class="">
          <label for="row">Row:</label>
          <input
            id="row"
            v-model="row"
            type="number"
            min="1"
            max="18"
            required
            class="border-gray-200 border-2 rounded"
            style="width: 50px"
          />
        </div>
        <div v-if="result !== null" class="my-4">
          <p>Result: {{ result }}</p>
        </div>
        <button type="submit" class="bg-gray-200">Decode</button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'Decoder',
  data() {
    return {
      column: '',
      row: null,
      result: null,
      mapping: {
        'A-1': 'G',
        'A-2': 'K',
        'A-3': 'W',
        'A-4': 'M',
        'A-5': 'P',
        'A-6': 'N',
        'A-7': 'R',
        'A-8': 'V',
        'A-9': 'S',
        'A-10': 'T',
        'A-11': 'Q',
        'A-12': 'T',
        'A-13': 'T',
        'A-14': 'D',
        'A-15': 'F',
        'A-16': 'C',
        'A-17': 'I',
        'A-18': 'J',
        'B-1': 'H',
        'B-2': 'L',
        'B-3': 'Q',
        'B-4': 'C',
        'B-5': 'M',
        'B-6': 'I',
        'B-7': 'D',
        'B-8': 'J',
        'B-9': 'E',
        'B-10': 'P',
        'B-11': 'R',
        'B-12': 'T',
        'B-13': 'T',
        'B-14': 'R',
        'B-15': 'V',
        'B-16': 'A',
        'B-17': 'N',
        'B-18': 'S',
        'C-1': 'W',
        'C-2': 'T',
        'C-3': 'N',
        'C-4': 'Q',
        'C-5': 'H',
        'C-6': 'L',
        'C-7': 'S',
        'C-8': 'K',
        'C-9': 'E',
        'C-10': 'M',
        'C-11': 'P',
        'C-12': 'J',
        'C-13': 'D',
        'C-14': 'I',
        'C-15': 'A',
        'C-16': 'V',
        'C-17': 'F',
        'C-18': 'G',
        'D-1': 'T',
        'D-2': 'S',
        'D-3': 'J',
        'D-4': 'N',
        'D-5': 'K',
        'D-6': 'P',
        'D-7': 'Q',
        'D-8': 'A',
        'D-9': 'L',
        'D-10': 'H',
        'D-11': 'M',
        'D-12': 'W',
        'D-13': 'G',
        'D-14': 'F',
        'D-15': 'V',
        'D-16': 'I',
        'D-17': 'R',
        'D-18': 'C',
        'E-1': 'K',
        'E-2': 'D',
        'E-3': 'R',
        'E-4': 'W',
        'E-5': 'S',
        'E-6': 'G',
        'E-7': 'P',
        'E-8': 'V',
        'E-9': 'I',
        'E-10': 'L',
        'E-11': 'A',
        'E-12': 'S',
        'E-13': 'A',
        'E-14': 'Q',
        'E-15': 'M',
        'E-16': 'F',
        'E-17': 'T',
        'E-18': 'J',
        'F-1': 'N',
        'F-2': 'Q',
        'F-3': 'P',
        'F-4': 'H',
        'F-5': 'L',
        'F-6': 'J',
        'F-7': 'K',
        'F-8': 'W',
        'F-9': 'G',
        'F-10': 'V',
        'F-11': 'M',
        'F-12': 'S',
        'F-13': 'D',
        'F-14': 'T',
        'F-15': 'A',
        'F-16': 'I',
        'F-17': 'R',
        'F-18': 'C',
        'G-1': 'M',
        'G-2': 'P',
        'G-3': 'K',
        'G-4': 'L',
        'G-5': 'S',
        'G-6': 'T',
        'G-7': 'J',
        'G-8': 'H',
        'G-9': 'D',
        'G-10': 'Q',
        'G-11': 'W',
        'G-12': 'V',
        'G-13': 'N',
        'G-14': 'F',
        'G-15': 'A',
        'G-16': 'R',
        'G-17': 'C',
        'G-18': 'I',
        'H-1': 'S',
        'H-2': 'W',
        'H-3': 'M',
        'H-4': 'P',
        'H-5': 'N',
        'H-6': 'K',
        'H-7': 'T',
        'H-8': 'L',
        'H-9': 'U',
        'H-10': 'D',
        'H-11': 'Q',
        'H-12': 'J',
        'H-13': 'V',
        'H-14': 'G',
        'H-15': 'I',
        'H-16': 'F',
        'H-17': 'R',
        'H-18': 'C',
        'I-1': 'P',
        'I-2': 'T',
        'I-3': 'G',
        'I-4': 'N',
        'I-5': 'W',
        'I-6': 'Q',
        'I-7': 'J',
        'I-8': 'R',
        'I-9': 'U',
        'I-10': 'D',
        'I-11': 'S',
        'I-12': 'H',
        'I-13': 'L',
        'I-14': 'A',
        'I-15': 'M',
        'I-16': 'V',
        'I-17': 'F',
        'I-18': 'C',
        'J-1': 'K',
        'J-2': 'H',
        'J-3': 'N',
        'J-4': 'D',
        'J-5': 'G',
        'J-6': 'M',
        'J-7': 'Q',
        'J-8': 'S',
        'J-9': 'U',
        'J-10': 'P',
        'J-11': 'R',
        'J-12': 'R',
        'J-13': 'R',
        'J-14': 'V',
        'J-15': 'A',
        'J-16': 'L',
        'J-17': 'F',
        'J-18': 'C',
        'K-1': 'N',
        'K-2': 'D',
        'K-3': 'P',
        'K-4': 'W',
        'K-5': 'S',
        'K-6': 'L',
        'K-7': 'E',
        'K-8': 'T',
        'K-9': 'I',
        'K-10': 'Q',
        'K-11': 'M',
        'K-12': 'A',
        'K-13': 'J',
        'K-14': 'V',
        'K-15': 'R',
        'K-16': 'F',
        'K-17': 'C',
        'K-18': 'G',
        'L-1': 'W',
        'L-2': 'T',
        'L-3': 'N',
        'L-4': 'S',
        'L-5': 'K',
        'L-6': 'J',
        'L-7': 'P',
        'L-8': 'Q',
        'L-9': 'I',
        'L-10': 'G',
        'L-11': 'H',
        'L-12': 'M',
        'L-13': 'R',
        'L-14': 'V',
        'L-15': 'A',
        'L-16': 'F',
        'L-17': 'I',
        'L-18': 'C',
        'M-1': 'P',
        'M-2': 'Q',
        'M-3': 'D',
        'M-4': 'K',
        'M-5': 'N',
        'M-6': 'G',
        'M-7': 'S',
        'M-8': 'T',
        'M-9': 'I',
        'M-10': 'L',
        'M-11': 'J',
        'M-12': 'D',
        'M-13': 'D',
        'M-14': 'V',
        'M-15': 'F',
        'M-16': 'R',
        'M-17': 'I',
        'M-18': 'C',
        'N-1': 'K',
        'N-2': 'M',
        'N-3': 'S',
        'N-4': 'L',
        'N-5': 'Q',
        'N-6': 'P',
        'N-7': 'H',
        'N-8': 'S',
        'N-9': 'D',
        'N-10': 'R',
        'N-11': 'J',
        'N-12': 'D',
        'N-13': 'D',
        'N-14': 'A',
        'N-15': 'F',
        'N-16': 'I',
        'N-17': 'W',
        'N-18': 'C',
        'O-1': 'D',
        'O-2': 'S',
        'O-3': 'S',
        'O-4': 'M',
        'O-5': 'L',
        'O-6': 'T',
        'O-7': 'Q',
        'O-8': 'P',
        'O-9': 'N',
        'O-10': 'A',
        'O-11': 'R',
        'O-12': 'I',
        'O-13': 'I',
        'O-14': 'I',
        'O-15': 'K',
        'O-16': 'V',
        'O-17': 'H',
        'O-18': 'G',
        'P-1': 'L',
        'P-2': 'D',
        'P-3': 'R',
        'P-4': 'T',
        'P-5': 'Q',
        'P-6': 'M',
        'P-7': 'S',
        'P-8': 'H',
        'P-9': 'N',
        'P-10': 'W',
        'P-11': 'G',
        'P-12': 'I',
        'P-13': 'I',
        'P-14': 'N',
        'P-15': 'A',
        'P-16': 'C',
        'P-17': 'I',
        'P-18': 'V',
        'Q-1': 'M',
        'Q-2': 'K',
        'Q-3': 'N',
        'Q-4': 'S',
        'Q-5': 'L',
        'Q-6': 'T',
        'Q-7': 'W',
        'Q-8': 'D',
        'Q-9': 'R',
        'Q-10': 'H',
        'Q-11': 'P',
        'Q-12': 'V',
        'Q-13': 'A',
        'Q-14': 'J',
        'Q-15': 'F',
        'Q-16': 'G',
        'Q-17': 'I',
        'Q-18': 'C',
        'R-1': 'H',
        'R-2': 'M',
        'R-3': 'T',
        'R-4': 'N',
        'R-5': 'W',
        'R-6': 'P',
        'R-7': 'J',
        'R-8': 'K',
        'R-9': 'Q',
        'R-10': 'L',
        'R-11': 'V',
        'R-12': 'S',
        'R-13': 'D',
        'R-14': 'A',
        'R-15': 'G',
        'R-16': 'F',
        'R-17': 'I',
        'R-18': 'C',
        'S-1': 'N',
        'S-2': 'Q',
        'S-3': 'L',
        'S-4': 'K',
        'S-5': 'J',
        'S-6': 'M',
        'S-7': 'T',
        'S-8': 'H',
        'S-9': 'L',
        'S-10': 'G',
        'S-11': 'D',
        'S-12': 'P',
        'S-13': 'A',
        'S-14': 'F',
        'S-15': 'I',
        'S-16': 'V',
        'S-17': 'R',
        'S-18': 'C',
        'T-1': 'V',
        'T-2': 'N',
        'T-3': 'Q',
        'T-4': 'S',
        'T-5': 'H',
        'T-6': 'W',
        'T-7': 'D',
        'T-8': 'P',
        'T-9': 'L',
        'T-10': 'A',
        'T-11': 'A',
        'T-12': 'G',
        'T-13': 'R',
        'T-14': 'A',
        'T-15': 'F',
        'T-16': 'M',
        'T-17': 'C',
        'T-18': 'I',
      },
    }
  },
  methods: {
    handleSubmit() {
      const column = this.column.toUpperCase()
      const row = this.row

      if (!/^[A-T]$/.test(column)) {
        alert('Column must be a letter from A to T.')
        return
      }

      if (row < 1 || row > 18) {
        alert('Row must be an integer between 1 and 18.')
        return
      }

      const key = `${column}-${row}`
      this.result = this.mapping[key] || 'Invalid combination'
    },
  },
}
</script>

<style scoped>
form {
  margin-bottom: 10px;
}

button {
  padding: 5px 10px;
}
</style>
